import { motion } from 'framer-motion'
import { ArrowRight, Code2, BrainCircuit, Search, ShieldCheck, Bot, Terminal } from 'lucide-react'
import Navbar from '../components/Navbar'

const features = [
  {
    title: 'Hallucination Detection',
    icon: Code2,
    description: 'Detect and block non-existent or "hallucinated" libraries often suggested by LLMs, preventing dependency hijacking and build failures.',
    color: '#22d3ee',
  },
  {
    title: 'Model Provenance',
    icon: BrainCircuit,
    description: 'Verify the lineage of open-source models used in your environment. Know exactly what versions of models are driving your internal code generation.',
    color: '#a78bfa',
  },
  {
    title: 'Shadow AI Auditing',
    icon: Search,
    description: 'Identify usage of unapproved code snippets generated by AI that bypass your existing security and quality controls.',
    color: '#60a5fa',
  },
]

const outcomes = [
  { title: 'Trust Your AI-Generated Code', description: 'Every line an LLM produces is validated against security patterns before it merges, so velocity never comes at the cost of safety.' },
  { title: 'Block Dependency Hijacking', description: 'Hallucinated package names are a known attack vector. Catch them before an attacker registers the name and ships malware.' },
  { title: 'Govern Model Usage', description: 'Know which models, versions, and providers are generating code across your org, and enforce policy on what is allowed.' },
  { title: 'Surface Shadow AI', description: 'Discover unapproved AI tools quietly producing code that skips your review process, and bring it under governance.' },
  { title: 'Keep Pipelines Secure', description: 'AI-native gates run inside CI/CD, so automated and agentic workflows stay protected without slowing engineers down.' },
  { title: 'Compliance for AI Acts', description: 'Generate the provenance and audit evidence regulators increasingly demand for AI-assisted software.' },
]

function FeatureCard({ item, index }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.4, delay: index * 0.05 }}
      className="rounded-xl border border-white/10 bg-white/5 p-6 hover:border-white/20 hover:bg-white/8 transition-all"
    >
      <div className="p-3 rounded-lg inline-flex mb-4" style={{ background: `${item.color}18`, border: `1px solid ${item.color}28` }}>
        <item.icon className="w-6 h-6" style={{ color: item.color }} />
      </div>
      <h3 className="text-lg font-bold text-white mb-2">{item.title}</h3>
      <p className="text-sm text-slate-400 leading-relaxed">{item.description}</p>
    </motion.div>
  )
}

function OutcomeCard({ outcome, index }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.4, delay: index * 0.05 }}
      className="rounded-xl border border-white/10 bg-white/5 p-6 hover:border-cyan-500/50 hover:bg-cyan-500/5 transition-all"
    >
      <div className="flex items-start gap-3 mb-3">
        <div className="w-2 h-2 rounded-full bg-cyan-400 mt-1 flex-shrink-0" />
        <h3 className="text-sm font-bold text-white">{outcome.title}</h3>
      </div>
      <p className="text-sm text-slate-400">{outcome.description}</p>
    </motion.div>
  )
}

export default function AISecurityPage() {
  return (
    <div className="min-h-screen bg-slate-950">
      <Navbar />

      {/* Hero */}
      <section className="pt-32 pb-20 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="lg:grid lg:grid-cols-2 lg:gap-12 items-center">
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 text-sm font-semibold mb-6">
                <Bot className="w-4 h-4" /> AI-Native Security Gate
              </div>
              <h1 className="text-5xl lg:text-6xl font-black text-white mb-6 leading-tight">
                Ship AI-generated code{' '}
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-indigo-400">without the hidden risk.</span>
              </h1>
              <p className="text-xl text-slate-300 mb-8 leading-relaxed">
                From hallucinated dependencies to insecure LLM patterns, Delivery Shield automatically validates every line of AI-generated code, ensuring your automated pipelines stay secure.
              </p>
              <div className="flex flex-col sm:flex-row gap-4">
                <a href="https://www.opsmx.com/talk-to-an-application-security-expert/" target="_blank" rel="noopener noreferrer" className="px-8 py-3 rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500 text-white font-semibold hover:from-cyan-400 hover:to-blue-400 transition-all duration-200 shadow-lg shadow-cyan-500/20 flex items-center justify-center gap-2">
                  Get a Demo <ArrowRight className="w-4 h-4" />
                </a>
                <button className="px-8 py-3 rounded-lg border border-white/20 text-white font-semibold hover:border-white/40 hover:bg-white/5 transition-all duration-200">
                  See How It Works
                </button>
              </div>
            </motion.div>

            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.2 }} className="mt-12 lg:mt-0">
              <div className="rounded-xl border border-white/10 bg-white/5 p-6">
                <div className="flex justify-between items-center mb-6 border-b border-white/10 pb-4">
                  <h3 className="text-slate-400 font-mono text-xs uppercase tracking-wider flex items-center gap-2">
                    <Terminal className="w-4 h-4" /> AI-Code Validation Engine
                  </h3>
                  <span className="text-cyan-400 font-mono text-xs animate-pulse">ACTIVE</span>
                </div>
                <div className="p-4 bg-slate-950 rounded-lg border border-cyan-500/20">
                  <p className="text-cyan-400 font-mono text-sm mb-3">SCANNING: ai-generated-snippet-72.js</p>
                  <div className="space-y-2">
                    <div className="flex items-center justify-between text-xs text-slate-400">
                      <span>Pattern Analysis</span><span className="text-emerald-400">Passed</span>
                    </div>
                    <div className="flex items-center justify-between text-xs text-slate-400">
                      <span>Dependency Hallucination Check</span><span className="text-rose-400">FAILED</span>
                    </div>
                    <div className="bg-rose-500/10 p-2 rounded text-rose-300 font-mono text-[11px] border border-rose-500/20">
                      Alert: Import 'express-v5-legacy' (Non-existent package)
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      <section className="py-20 px-6 bg-white/2">
        <div className="max-w-6xl mx-auto">
          <motion.h2 initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} transition={{ duration: 0.5 }} className="text-4xl font-black text-white mb-12 text-center">
            Three Pillars of AI Code Security
          </motion.h2>
          <div className="grid md:grid-cols-3 gap-6">
            {features.map((item, idx) => <FeatureCard key={idx} item={item} index={idx} />)}
          </div>
        </div>
      </section>

      <section className="py-20 px-6">
        <div className="max-w-5xl mx-auto">
          <motion.h2 initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} transition={{ duration: 0.5 }} className="text-4xl font-black text-white mb-12 text-center">
            What You Get
          </motion.h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {outcomes.map((outcome, idx) => <OutcomeCard key={idx} outcome={outcome} index={idx} />)}
          </div>
        </div>
      </section>

      <section className="py-20 px-6 bg-gradient-to-b from-cyan-950/20 to-slate-950">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div initial={{ opacity: 0, scale: 0.95 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ duration: 0.5 }}>
            <h2 className="text-4xl font-black text-white mb-4">Govern Your AI Pipeline</h2>
            <p className="text-lg text-slate-300 mb-8">See how Delivery Shield validates AI-generated code before it ships.</p>
            <a href="https://www.opsmx.com/talk-to-an-application-security-expert/" target="_blank" rel="noopener noreferrer" className="px-8 py-3 rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500 text-white font-semibold hover:from-cyan-400 hover:to-blue-400 transition-all duration-200 shadow-lg shadow-cyan-500/20 inline-flex items-center justify-center gap-2">
              Schedule a Demo <ArrowRight className="w-4 h-4" />
            </a>
          </motion.div>
        </div>
      </section>
    </div>
  )
}
